apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcano-volume-claim
spec:
  storageClassName: sistemaficheros
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi