apiVersion: v1
kind: PersistentVolume
metadata:
  name: pcano-volume
  labels:
    type: local
spec:
  storageClassName: sistemaficheros
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"